#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo  "🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮 ";
    echo  "${RED}ERROR: Prettier Check Failed!${NC}";
    echo  "Run ${YELLOW}npm run format${NC}, add changes and try commit again.";
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 Make the required changes listed above, add changes and try to commit again.'
            echo  "${RED}ERROR: ESLint Check Failed${NC}";
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.';
     echo  "${RED}ERROR: Failed Type check.${NC}";
    false;
)

# If everything passes... Now we can commit
echo "🤔🤔🤔🤔... ${LIGHTGREEN}Alright... Code looks good to me... Trying to build now.${NC} 🤔🤔🤔🤔"

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo "✅✅✅✅ ${LIGHTGREEN}You win this time... I am committing this now.${NC} ✅✅✅✅"

npm run lint-staged
